### ISSUE TITLE
Scipy package in dependencies is missing libgfortran

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastik-build-conda#17]
FYI: when one sets up conda afresh on a linux machine (noticed it on two Ubuntu 14.04 boxes, one of them my CircleCI bot...) and installs `ilastik-everything-but-tracking`, the provided scipy version is `0.16.0`. But that one messed something up between gfortran and mkl (as @jakirkham found out at some point).

``` pytb
Traceback (most recent call last):
  File "/home/ubuntu/hytra/scripts/hypotheses_graph_to_json.py", line 13, in <module>
    import hytra.core.hypothesesgraph as hypothesesgraph
  File "/home/ubuntu/hytra/hytra/core/hypothesesgraph.py", line 2, in <module>
    from sklearn.neighbors import KDTree
  File "/home/ubuntu/miniconda/envs/test-env/lib/python2.7/site-packages/sklearn/neighbors/__init__.py", line 6, in <module>
    from .ball_tree import BallTree
  File "ball_tree.pyx", line 1, in init sklearn.neighbors.ball_tree (sklearn/neighbors/ball_tree.c:35730)
  File "/home/ubuntu/miniconda/envs/test-env/lib/python2.7/site-packages/sklearn/utils/__init__.py", line 16, in <module>
    from .class_weight import compute_class_weight, compute_sample_weight
  File "/home/ubuntu/miniconda/envs/test-env/lib/python2.7/site-packages/sklearn/utils/class_weight.py", line 7, in <module>
    from ..utils.fixes import in1d
  File "/home/ubuntu/miniconda/envs/test-env/lib/python2.7/site-packages/sklearn/utils/fixes.py", line 318, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr
  File "/home/ubuntu/miniconda/envs/test-env/lib/python2.7/site-packages/scipy/sparse/linalg/__init__.py", line 109, in <module>
    from .isolve import *
  File "/home/ubuntu/miniconda/envs/test-env/lib/python2.7/site-packages/scipy/sparse/linalg/isolve/__init__.py", line 6, in <module>
    from .iterative import *
  File "/home/ubuntu/miniconda/envs/test-env/lib/python2.7/site-packages/scipy/sparse/linalg/isolve/iterative.py", line 7, in <module>
    from . import _iterative
ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory
```

I had to manually switch to `scipy=0.17.0=np19py27_2` (see e.g. https://github.com/chaubold/hytra/commit/939e5aefcee86559ef9fa0f80cf913e84852354c).

**Comment by stuarteberg** [comment]
The title here says 'sklearn', but the commit you referenced says 'scipy'.  Is there a typo in the title, or am I confused?

**Comment by chaubold** [comment]
Oops, sorry, you're right, it was supposed to be _scipy_ everywhere. Fixed in title and message above.

**Comment by akreshuk** [comment]
Here is the discussion at anaconda-issues: https://github.com/ContinuumIO/anaconda-issues/issues/686. Force-installing libgrfortran==1 worked for me.

**Comment by k-dominik** [comment]
not an issue anymore
