### ISSUE TITLE
ilastik-feature-selection dependency missing somewhere

### ISSUE THREAD

**Issue by svenpeter42** [ilastik/ilastik-build-conda#20]
```
(miniconda) speter@speter-laptop ~ 
% conda create --name ilastik-ff-test ilastik-everything-but-tracking
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/speter/miniconda2/envs/ilastik-ff-test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    faulthandler-2.4           |           py27_0          32 KB
    ilastik-meta-1.2.0rc7      |       0_g16aaa7c         7.4 MB  ilastik
    six-1.10.0                 |           py27_0          16 KB
    iiboost-0.2.post2          |27_0_76140cd985ab301749395bb47cbc8f8d88cdd257         277 KB  ilastik
    scipy-0.18.0               |      np111py27_0        31.0 MB
    tifffile-0.4.1             |np111py27_2_g05b51f3         107 KB  ilastik
    ilastiktools-0.2           |np111py27_0_g731565e         116 KB  ilastik
    qimage2ndarray-1.4         |      np111py27_5          20 KB  ilastik
    ilastik-deps-pc-headless-1.1|           py27_4          902 B  ilastik
    ilastik-deps-pc-1.1        |           py27_3          894 B  ilastik
    ilastik-deps-carving-1.1.6a7|                1          605 B  ilastik
    ilastik-deps-pc-iiboost-1.1|                1          588 B  ilastik
    ilastik-everything-but-tracking-1.2.0rc3|                0           1 KB  ilastik
    ------------------------------------------------------------
                                           Total:        39.0 MB

The following NEW packages will be INSTALLED:

    boost:                           1.55.0-5                                                ilastik
    cairo:                           1.12.18-6                                                      
    cycler:                          0.10.0-py27_0                                                  
    decorator:                       4.0.10-py27_0                                                  
    faulthandler:                    2.4-py27_0                                                     
    fftw:                            3.3.4-1                                                 ilastik
    fontconfig:                      2.11.1-6                                                       
    freetype:                        2.5.5-1                                                        
    functools32:                     3.2.3.2-py27_0                                                 
    futures:                         3.0.5-py27_0                                                   
    greenlet:                        0.4.10-py27_0                                                  
    h5py:                            2.6.0-np111py27_1                                              
    hdf5:                            1.8.16-0                                                       
    iiboost:                         0.2.post2-27_0_76140cd985ab301749395bb47cbc8f8d88cdd257 ilastik
    ilastik-deps-carving:            1.1.6a7-1                                               ilastik
    ilastik-deps-pc:                 1.1-py27_3                                              ilastik
    ilastik-deps-pc-headless:        1.1-py27_4                                              ilastik
    ilastik-deps-pc-iiboost:         1.1-1                                                   ilastik
    ilastik-everything-but-tracking: 1.2.0rc3-0                                              ilastik
    ilastik-launch:                  0.1-4                                                   ilastik
    ilastik-meta:                    1.2.0rc7-0_g16aaa7c                                     ilastik
    ilastiktools:                    0.2-np111py27_0_g731565e                                ilastik
    itk-seg-conv-only:               4.6.1-4                                                 ilastik
    jbig:                            2.1-0                                                   ilastik
    jpeg:                            8d-1                                                           
    jsonschema:                      2.5.1-py27_0                                                   
    libgcc:                          4.8.5-1                                                        
    libgfortran:                     3.0.0-1                                                        
    libpng:                          1.6.17-0                                                       
    libtiff:                         4.0.6-1                                                 ilastik
    libxml2:                         2.9.2-0                                                        
    matplotlib:                      1.5.1-np111py27_0                                              
    mkl:                             11.3.3-0                                                       
    networkx:                        1.11-py27_0                                                    
    nose:                            1.3.7-py27_1                                                   
    numpy:                           1.11.1-py27_0                                                  
    openssl:                         1.0.2h-1                                                       
    pillow:                          3.3.0-py27_0                                                   
    pip:                             8.1.2-py27_0                                                   
    pixman:                          0.32.6-0                                                       
    psutil:                          4.3.0-py27_0                                                   
    pycairo:                         1.10.0-py27_0                                                  
    pyparsing:                       2.1.4-py27_0                                                   
    pyqt:                            4.11.3-py27_1                                                  
    python:                          2.7.12-1                                                       
    python-dateutil:                 2.5.3-py27_0                                                   
    pytz:                            2016.6.1-py27_0                                                
    qimage2ndarray:                  1.4-np111py27_5                                         ilastik
    qt:                              4.8.6-3                                                        
    readline:                        6.2-2                                                          
    scikit-image:                    0.12.3-np111py27_1                                             
    scikit-learn:                    0.17.1-np111py27_2                                             
    scipy:                           0.18.0-np111py27_0                                             
    setuptools:                      23.0.0-py27_0                                                  
    sip:                             4.16.5-py27_0                                                  
    six:                             1.10.0-py27_0                                                  
    sqlite:                          3.13.0-0                                                       
    tifffile:                        0.4.1-np111py27_2_g05b51f3                              ilastik
    tk:                              8.5.18-0                                                       
    vigra:                           1.11.0.post36-np111py27_1_g6fcc71f                      ilastik
    vtk:                             5.10.1.99-with_pyqt_6                                   ilastik
    wheel:                           0.29.0-py27_0                                                  
    xz:                              5.2.2-0                                                        
    yapsy:                           1.10.423-py27_0                                         ilastik
    zlib:                            1.2.8-3                                                        

Proceed ([y]/n)? 

```

then inside the new env:

```
(ilastik-ff-test) speter@speter-laptop ~/miniconda2/envs/ilastik-ff-test 
% ./run_ilastik.sh 
Warning: Ignoring your non-empty QT_PLUGIN_PATH
Starting ilastik from "/home/speter/miniconda2/envs/ilastik-ff-test".
ERROR 2016-07-28 14:20:10,772 excepthooks 30125 139639445841664 Unhandled exception in thread: 'MainThread'
ERROR 2016-07-28 14:20:10,773 excepthooks 30125 139639445841664 Traceback (most recent call last):
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/ilastik/ilastik/shell/gui/startShellGui.py", line 91, in launchShell
    from ilastik.shell.gui.ilastikShell import IlastikShell
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 81, in <module>
    import ilastik.workflows
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/ilastik/ilastik/workflows/__init__.py", line 28, in <module>
    import pixelClassification
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/ilastik/ilastik/workflows/pixelClassification/__init__.py", line 21, in <module>
    from pixelClassificationWorkflow import PixelClassificationWorkflow
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/ilastik/ilastik/workflows/pixelClassification/pixelClassificationWorkflow.py", line 34, in <module>
    from ilastik.applets.pixelClassification import PixelClassificationApplet, PixelClassificationDataExportApplet
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/ilastik/ilastik/applets/pixelClassification/__init__.py", line 21, in <module>
    from pixelClassificationApplet import *
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/ilastik/ilastik/applets/pixelClassification/pixelClassificationApplet.py", line 22, in <module>
    from opPixelClassification import OpPixelClassification
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/ilastik/ilastik/applets/pixelClassification/opPixelClassification.py", line 36, in <module>
    import ilastik_feature_selection
ImportError: No module named ilastik_feature_selection
```

which can be fixed with

`% conda install ilastik-feature-selection`

**Comment by m-albert** [comment]
Or
`conda install --channel https://conda.anaconda.org/ilastik ilastik-feature-selection`

**Comment by stuarteberg** [comment]
Thanks for the reports, guys.  One of our packages on anaconda.org was out-of-date.  It's fixed now.
