### ISSUE TITLE
create ilastik-everything-no-solvers fails

### ISSUE THREAD

**Issue by ilastikdev** [ilastik/ilastik-build-conda#30]
```
(root)jales@seagul:~/software/miniconda$ conda create -n ilastik-devel -c ilastik ilastik-everything-no-solvers
Fetching package metadata: ......
Solving package specifications: .An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/jales/software/miniconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/jales/software/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/home/jales/software/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/home/jales/software/miniconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 50, in execute
    install.install(args, parser, 'create')
  File "/home/jales/software/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 334, in install
    minimal_hint=args.alt_hint)
  File "/home/jales/software/miniconda/lib/python2.7/site-packages/conda/plan.py", line 377, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/home/jales/software/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 746, in solve
    minimal_hint=minimal_hint)
  File "/home/jales/software/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 484, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/home/jales/software/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 342, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: ilastik-versions-no-solvers-1.2-np112py27_20.tar.bz2 MatchSpec(u'ann 1.1.2')


```

**Comment by stuarteberg** [comment]
Let me know what version of conda and conda-build you're using.

**Comment by ilastikdev** [comment]
```
(ilastik-devel) (root)jales@seagul:~/software$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.10.1
  conda-build version : not installed
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /home/jales/miniconda  (writable)
  default environment : /home/jales/miniconda/envs/ilastik-devel
     envs directories : /home/jales/miniconda/envs
        package cache : /home/jales/miniconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False


```

**Comment by stuarteberg** [comment]
Ah ok, somehow your version of conda is over 2 years old.  If you update to conda 4.3.x, does the error remain?

I wonder if perhaps your conda version is stuck on that old version due to some conflicting dependency in your root environment.  I'm not sure if that can happen, but using this command should reveal the answer:

```
conda install conda=4.3.18
```

If that fails due to some conflicting package in your root environment, remove the offending package and try again.  If all else fails, download a fresh version of miniconda and start from scratch.

**Comment by ilastikdev** [comment]
I was downloading a fresh version of miniconda so maybe our link points to an old 
'miniconda-latest-linux'
wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh

**Comment by stuarteberg** [comment]
>I was downloading a fresh version of miniconda so maybe our link points to an old 'miniconda-latest-linux'

Ah.  Good catch.  I [ran into this issue myself last year](https://groups.google.com/a/continuum.io/d/msg/conda/cK1a4Cewvdc/24Pgos22AwAJ) with the links on Continuum's own website, so I'm a little embarrassed I didn't think of it here.

The new link has an extra '2' in the name:
https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh

I've now updated the links in our README to match.
